services:


  backend:
    tty: true
    build:
      context: ../../code/backend
      dockerfile: ../../ops/docker/backend/dev/Dockerfile
    volumes:
      - ../../code/backend:/app
      - ../../ops:/ops
    restart: on-failure
    depends_on:
      - database

   #mongo:
   # image: mongo:4.2.24-bionic
   # restart: always
   # volumes:
   #   - mongo_db:/data/db
   # healthcheck:
   #   test: mongo --eval "print(\"waited for connection\")"
   #   interval: 5s
   #   timeout: 10s
   #   retries: 5

  #mongo-express:
  #  image: mongo-express:0.54
  #  restart: always


  #  rabbitmq:
  #    image: rabbitmq:3.11-management
  #    ports:
  #      - "5672:5672"
  #      - "15672:15672"


  database:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=verysecretpass
    restart: always
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=verysecretpass" ]
      interval: 5s
      timeout: 10s
      retries: 5

#  vue:
#    build:
#      context: ../../code/frontend
#      dockerfile: ../../ops/docker/vue/dev/Dockerfile
#    tty: true
#    volumes:
#      - ../../code/frontend:/app
#      - node_modules:/app/node_modules
#    restart: always


volumes:
  landing-vendor:
  db:
  mongo_db: