services:

  backend:
    ports:
      - "8080:8000"

  #mongo:
  #  ports:
  #    - "27017:27017"
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: verysecretpass
  #  networks:
  #    - sequra

  #mongo-express:
  #  ports:
  #    - "8888:8081"
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: verysecretpass
  #    ME_CONFIG_MONGODB_URL: mongodb://root:verysecretpass@mongo:27017/


  #database:
  #  ports:
  #    - "3306:3306"

#  vue:
#    ports:
#      - "5173:5173"
#    environment:
#      - VUE_APP_BASE_URL="http://localhost:8080"
